import { Instruction } from "../interpreter/constants";

export const IntermediateObject = [
  { op: "=", result: "numBloco", operand1: "0", operand2: null },
  { op: "=", result: "divBloco", operand1: "0", operand2: null },
  { op: "=", result: "restoBloco", operand1: "0", operand2: null },
  {
    op: "CALL",
    result: "PRINT",
    operand1: '"Entre com o inteiro: "',
    operand2: null,
  },
  { op: "CALL", result: "SCAN", operand1: null, operand2: "numBloco" },
  { op: "CALL", result: "PRINT", operand1: null, operand2: "numBloco" },
  { op: "CALL", result: "PRINT", operand1: '" = "', operand2: null },
  { op: "LABEL", result: "__label0", operand1: null, operand2: null },
  { op: ">", result: "__temp0", operand1: "numBloco", operand2: "1" },
  {
    op: "IF",
    result: "__temp0",
    operand1: "__label1",
    operand2: "__label2",
  },
  { op: "LABEL", result: "__label1", operand1: null, operand2: null },
  { op: "=", result: "divBloco", operand1: "2", operand2: null },
  { op: "LABEL", result: "__label3", operand1: null, operand2: null },
  {
    op: "%",
    result: "__temp1",
    operand1: "numBloco",
    operand2: "divBloco",
  },
  { op: "<>", result: "__temp2", operand1: "__temp1", operand2: "0" },
  {
    op: "IF",
    result: "__temp2",
    operand1: "__label4",
    operand2: "__label5",
  },
  { op: "LABEL", result: "__label4", operand1: null, operand2: null },
  { op: "+", result: "__temp3", operand1: "divBloco", operand2: "1" },
  { op: "=", result: "divBloco", operand1: "__temp3", operand2: null },
  { op: "JUMP", result: "__label3", operand1: null, operand2: null },
  { op: "LABEL", result: "__label5", operand1: null, operand2: null },
  { op: "CALL", result: "PRINT", operand1: null, operand2: "divBloco" },
  {
    op: "/",
    result: "__temp4",
    operand1: "numBloco",
    operand2: "divBloco",
  },
  { op: "=", result: "numBloco", operand1: "__temp4", operand2: null },
  { op: ">", result: "__temp5", operand1: "numBloco", operand2: "1" },
  {
    op: "IF",
    result: "__temp5",
    operand1: "__label6",
    operand2: "__label7",
  },
  { op: "LABEL", result: "__label6", operand1: null, operand2: null },
  { op: "CALL", result: "PRINT", operand1: '" * "', operand2: null },
  { op: "JUMP", result: "__label8", operand1: null, operand2: null },
  { op: "LABEL", result: "__label7", operand1: null, operand2: null },
  { op: "LABEL", result: "__label8", operand1: null, operand2: null },
  { op: "JUMP", result: "__label0", operand1: null, operand2: null },
  { op: "LABEL", result: "__label2", operand1: null, operand2: null },
  { op: "CALL", result: "PRINT", operand1: '"\n"', operand2: null },
  {
    op: "CALL",
    result: "PRINT",
    operand1: '"finalizando"',
    operand2: null,
  },
  { op: "CALL", result: "STOP", operand1: null, operand2: null },
] as Instruction[];
